version: "3"

volumes:
  db_data:
  recording_data:
    driver: local
networks:
  new:
    driver: bridge
services:
  guacd:
    image: guacamole/guacd:0.9.14
    networks:
      - new
    environment:
      GUACDHOST: guacd
      REDISHOST: redis
      WEBTERMINALHOST: webterminal
    restart: always
    volumes:
      - recording_data:/opt/webterminal/media/
    ports:
      - "4822:4822"
  redis:
    image: redis:6.0-alpine
    networks:
      - new
    restart: always
    ports:
      - "6379:6379"
  webterminal:
    image: webterminal/webterminal:beta
    networks:
      - new
    environment:
      GUACDHOST: guacd
      REDISHOST: redis
    restart: always
    volumes:
      - recording_data:/opt/webterminal/media/
      - db_data:/opt/webterminal/db/
    ports:
      - "9001:80"
      - "2100:2100"
  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    networks:
      - new
    restart: always
    volumes:
      - /var/cloudbeaver/workspace:/opt/cloudbeaver/workspace
    ports:
      - "8080:8978"
  frpc:
    image: snowdreamtech/frpc
    networks:
      - new
    network_mode: host
    restart: always
    volumes:
      - /data/frpc.ini:/etc/frp/frpc.ini